apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    name: app-demo
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: AppProject
    - group: argoproj.io
      kind: ApplicationSet
    - group: '*'
      kind: Secret
    - group: '*'
      kind: PersistentVolumeClaim
    - group: '*'
      kind: Pipeline
    - group: '*'
      kind: ServiceAccount
    - group: '*'
      kind: LimitRange
    - group: "*"
      kind: ResourceQuota

    destinations:
    - namespace: openshift-gitops
      server: https://kubernetes.default.svc
    - namespace: app-demo-dev
      server: https://kubernetes.default.svc
    - namespace: app-demo-test
      server: https://kubernetes.default.svc
    - namespace: app-demo-pre
      server: https://kubernetes.default.svc
    namespaceResourceBlacklist:
    - group: ""
      kind: NetworkPolicy
    sourceRepos:
    - '*'
- apiVersion: argoproj.io/v1alpha1
  kind: ApplicationSet
  metadata:
    name: app-demo-set
  spec:
    generators:
    - list:
        elements:
        - env: dev
          project: app-demo
        - env: test
          project: app-demo
        - env: pre
          project: app-demo
    template:
      metadata:
        finalizers:
        - resources-finalizer.argocd.argoproj.io
        name: '{{project}}-{{env}}'
        namespace: openshift-gitops
      spec:
        destination:
          namespace: '{{project}}-{{env}}'
          server: https://kubernetes.default.svc
        project: '{{project}}'
        source:
          directory:
            recurse: true
          path: ocp1/projects/{{project}}/{{env}}
          repoURL: ssh://git@github.com/jeanpaullb/app-demo-gitops.git
          targetRevision: master
        syncPolicy:
          syncOptions:
          - Validate=false
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    finalizers: 
    - resources-finalizer.argocd.argoproj.io
    name: app-demo-dev
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
    - group: '*'
      kind: Secret
    - group: '*'
      kind: PersistentVolumeClaim
    - group: '*'
      kind: Pipeline
    - group: '*'
      kind: ServiceAccount
    - group: '*'
      kind: LimitRange
    - group: "*"
      kind: ResourceQuota
    destinations:
    - namespace: app-demo-dev
      server: https://kubernetes.default.svc
    namespaceResourceBlacklist:
    - group: ""
      kind: NetworkPolicy
    sourceRepos:
    - '*'
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    name: app-demo-test
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
    - group: '*'
      kind: Secret
    - group: '*'
      kind: PersistentVolumeClaim
    - group: '*'
      kind: Pipeline
    - group: '*'
      kind: ServiceAccount
    - group: '*'
      kind: LimitRange
    - group: "*"
      kind: ResourceQuota
    destinations:
    - namespace: app-demo-test
      server: https://kubernetes.default.svc
    namespaceResourceBlacklist:
    - group: ""
      kind: NetworkPolicy
    sourceRepos:
    - '*'

- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    name: app-demo-pre
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
    - group: '*'
      kind: Secret
    - group: '*'
      kind: PersistentVolumeClaim
    - group: '*'
      kind: Pipeline
    - group: '*'
      kind: ServiceAccount
    - group: '*'
      kind: LimitRange
    - group: "*"
      kind: ResourceQuota
    destinations:
    - namespace: app-demo-pre
      server: https://kubernetes.default.svc
    namespaceResourceBlacklist:
    - group: ""
      kind: NetworkPolicy
    sourceRepos:
    - '*'
