apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings
data:
  settings.xml: |
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                              http://maven.apache.org/xsd/settings-1.0.0.xsd">

      <!-- Credenciales para autenticación -->
      <servers>
          <server>
              <id>nexus-demo</id>
              <username>admin</username>
              <password>admin123</password>
          </server>
      </servers>

      <mirrors>
          <mirror>
              <id>nexus</id>
              <mirrorOf>*</mirrorOf>
              <url>http://nexus-nexus.apps.cluster-zg2lr.zg2lr.sandbox984.opentlc.com/repository/maven-public/</url>
          </mirror>
      </mirrors>
    </settings>