apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-resource-management
rules:
- apiGroups: [""]
  # Permitir acciones en LimitRange
  resources: ["limitranges"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  # Permitir acciones en ResourceQuotas
  resources: ["resourcequotas"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-cluster-task-management
rules:
  - verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete
    apiGroups:
      - tekton.dev
    resources:
      - clustertasks
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-cicd-resources
rules:
  - verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete
    apiGroups:
      - tekton.dev
    resources:
      - clustertasks
      - pipelineruns
      - pipelines
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sealed-secret-create
rules:
  - verbs:
      - get
      - create
      - patch
      - delete
      - update
    apiGroups:
      - 'bitnami.com'
    resources:
      - sealedsecrets
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-puller
rules:
  - verbs:
      - get
    apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
      - imagestreams/layers
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: openshift-pipelines
  name: cronjob-cleanup-edit
rules:
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - tekton.dev
    resources:
      - tasks
      - taskruns
      - pipelines
      - pipelineruns
      - pipelineresources
      - conditions
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - operator.tekton.dev
    resources:
      - tektonpipelines
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - tekton.dev
    resources:
      - tasks
      - taskruns
      - pipelines
      - pipelineruns
      - pipelineresources
      - conditions
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - tekton.dev
    resources:
      - clustertasks
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - operator.tekton.dev
    resources:
      - tektonpipelines